[project]
name = "jeffersonstats"
version = "0.1.0"
description = "An MCP server for statitics"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.10.1",
    "numpy>=2.3.1",
    "scipy>=1.16.0",
    "scipy-stubs>=1.16.0.2",
]
